#%RAML 0.8
---
title: Checklister
version: 1.0
baseUri: kiramishima.koding.io:3000/api
documentation:
    - title: Getting Started
      contents: | 
        This sample API has been created as part of your project.
/organization
/users
/teams:
    displayName: Teams
/team_members
/login
/signup